export enum WorkerState {
  IDLE = 'IDLE',
  WAITING = 'WAITING',
  CLAIMING = 'CLAIMING',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  FAILED = 'FAILED',
}

export enum JobLifecycle {
  QUEUED = 'QUEUED',
  CLAIMED = 'CLAIMED',
  INITIALIZING = 'INITIALIZING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  TIMEOUT = 'TIMEOUT',
}

export enum QueueEventType {
  ENQUEUED = 'ENQUEUED',
  CLAIMED = 'CLAIMED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  TIMEOUT = 'TIMEOUT',
}
