export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  PROJECT_DETAIL: (slug: string) => `/projects/${slug}`,
  PROJECT_EDIT: (slug: string) => `/projects/${slug}/edit`,
  TEST_CASES: '/test-cases',
  TEST_CASE_DETAIL: (slug: string, code: string) => `/projects/${slug}/test-cases/${code}`,
  AUTOMATION: '/automation',
  EXECUTIONS: '/executions',
  EXECUTION_DETAIL: (id: string) => `/executions/${id}`,
  REPORTS: '/reports',
  PROFILE: '/profile',
  SETTINGS: '/settings',
};
