export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  PROJECT_CREATE: '/projects/create',
  PROJECT_OVERVIEW: (slug: string) => `/projects/${slug}`,
  PROJECT_EDIT: (slug: string) => `/projects/${slug}/edit`,
  PROJECT_TEST_CASES: (slug: string) => `/projects/${slug}/test-cases`,
  PROJECT_TEST_CASE_DETAIL: (slug: string, code: string) => `/projects/${slug}/test-cases/${code}`,
  PROJECT_AUTOMATION: (slug: string) => `/projects/${slug}/automation`,
  PROJECT_EXECUTIONS: (slug: string) => `/projects/${slug}/executions`,
  PROJECT_REPORTS: (slug: string) => `/projects/${slug}/reports`,
  EXECUTION_DETAIL: (id: string) => `/executions/${id}`,
  SETTINGS: '/settings',
};
