export const API = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/change-password',
  },
  USERS: {
    BASE: '/users',
    DETAIL: (id: string) => `/users/${id}`,
    ROLES: '/users/roles',
    RESET_PASSWORD: (id: string) => `/users/${id}/reset-password`,
    ACTIVATE: (id: string) => `/users/${id}/activate`,
    DEACTIVATE: (id: string) => `/users/${id}/deactivate`,
    CHANGE_ROLE: (id: string) => `/users/${id}/change-role`,
  },
  PROJECTS: {
    BASE: '/projects',
    DETAIL: (id: string) => `/projects/${id}`,
    MEMBERS: (id: string) => `/projects/${id}/members`,
    MEMBER_DETAIL: (projectId: string, userId: string) => `/projects/${projectId}/members/${userId}`,
    AVAILABLE_MEMBERS: (id: string) => `/projects/${id}/available-members`,
  },
  TEST_CASES: {
    BASE: '/test-cases',
    DETAIL: (id: string) => `/test-cases/${id}`,
    BY_CODE: (code: string) => `/test-cases/code/${code}`,
    DUPLICATE: (id: string) => `/test-cases/${id}/duplicate`,
    CLONE: (id: string) => `/test-cases/${id}/clone`,
    STEPS: (id: string) => `/test-cases/${id}/steps`,
    STEPS_REORDER: (id: string) => `/test-cases/${id}/steps/reorder`,
    STEP_DETAIL: (testCaseId: string, stepNumber: number) => `/test-cases/${testCaseId}/steps/${stepNumber}`,
  },
  TEST_RUNS: {
    BASE: '/test-runs',
    DETAIL: (id: string) => `/test-runs/${id}`,
    START: (id: string) => `/test-runs/${id}/start`,
    FINISH: (id: string) => `/test-runs/${id}/finish`,
    STATISTICS: (id: string) => `/test-runs/${id}/statistics`,
    EXECUTIONS: (testRunId: string) => `/test-runs/${testRunId}/executions`,
    EXECUTION_DETAIL: (testRunId: string, testCaseId: string) => `/test-runs/${testRunId}/executions/${testCaseId}`,
  },
  BUGS: {
    BASE: '/bugs',
    DETAIL: (id: string) => `/bugs/${id}`,
    ASSIGN: (id: string) => `/bugs/${id}/assign`,
    IN_PROGRESS: (id: string) => `/bugs/${id}/in-progress`,
    RESOLVE: (id: string) => `/bugs/${id}/resolve`,
    CLOSE: (id: string) => `/bugs/${id}/close`,
    REOPEN: (id: string) => `/bugs/${id}/reopen`,
    COMMENTS: (bugId: string) => `/bugs/${bugId}/comments`,
    COMMENT_DETAIL: (bugId: string, commentId: string) => `/bugs/${bugId}/comments/${commentId}`,
    ATTACHMENTS: (bugId: string) => `/bugs/${bugId}/attachments`,
    ATTACHMENT_DETAIL: (bugId: string, attachmentId: string) => `/bugs/${bugId}/attachments/${attachmentId}`,
    HISTORY: (bugId: string) => `/bugs/${bugId}/history`,
    STATISTICS: '/bugs/statistics',
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    DETAIL: (id: string) => `/notifications/${id}`,
    MARK_READ: '/notifications/mark-read',
    MARK_ALL_READ: '/notifications/mark-all-read',
    UNREAD_COUNT: '/notifications/unread-count',
  },
};
