export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  PROJECT_DETAIL: (id: string) => `/projects/${id}`,
  TEST_CASES: '/test-cases',
  TEST_CASE_DETAIL: (id: string) => `/test-cases/${id}`,
  TEST_RUNS: '/test-runs',
  TEST_RUN_DETAIL: (id: string) => `/test-runs/${id}`,
  EXECUTIONS: '/executions',
  EXECUTION_DETAIL: (id: string) => `/executions/${id}`,
  BUGS: '/bugs',
  BUG_DETAIL: (id: string) => `/bugs/${id}`,
  USERS: '/users',
  USER_DETAIL: (id: string) => `/users/${id}`,
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  SETTINGS: '/settings',
};